name: Check Dependabot Alerts
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

permissions:
  security-events: read # Required for Dependabot access

jobs:
  check-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Alerts
        id: fetch-alerts
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.DEPENDABOT}} # Authentication
        run: |
          # Single-line jq filter avoids heredoc issues
          ALERTS_JSON=$(gh api --paginate "/repos/$GH_REPO/dependabot/alerts?state=open" \
            --jq 'map(select((.created_at | fromdateiso8601) > (now - 86400))')

          echo "alerts_json=$ALERTS_JSON" >> $GITHUB_OUTPUT

      - name: Process Alerts
        if: steps.fetch-alerts.outputs.alerts_json != '[]'
        run: |
          echo "New alerts: ${{ steps.fetch-alerts.outputs.alerts_json }}"
          # Add notifications (Slack/Email/etc.) here
