name: Create Asana Ticket for Dependabot Alerts

on:
  repository_advisory:
    types: [created]

jobs:
  create-asana-task:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    steps:
      - name: Create Asana Task
        uses: honeycombio/gha-create-asana-task@main
        with:
          #asana-secret: ${{ secrets.ASANA_PAT }}
          asana-secret: 2/1207429301186131/1209370901760232:60206bd5140e2000ae39a1f75f21a90f
          #asana-workspace-id: ${{ secrets.ASANA_WORKSPACE_ID }}
          asana-workspace-id: 1209370921355179
          #asana-project-id: ${{ secrets.ASANA_PROJECT_ID }}
          asana-project-id: 1209370898900553
          asana-task-name: "Dependabot Alert: ${{ github.event.alert.affected_package }}"
          #asana-section-id: ${{ secrets.ASANA_SECTION_ID }}
          asana-section-id: 1209370921355183
          asana-task-description: |
            **Package:** ${{ github.event.alert.affected_package }}
            **Severity:** ${{ github.event.alert.security_advisory.severity }}
            **Summary:** ${{ github.event.alert.security_advisory.summary }}
            **Alert URL:** [${{ github.event.alert.html_url }}](${{ github.event.alert.html_url }})
