name: Dependabot Alert Checker

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC
  workflow_dispatch:

jobs:
  check_dependabot_alerts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get dependabot alerts from GitHub API
        env:
          GH_TOKEN: ${{ secrets.DEPENDABOT}} # Explicitly use the GITHUB_TOKEN
        run: |
          gh api repos/ZainMI/Cardiac-Rehab-Visualization/dependabot/alerts \
            --jq '.[] | select(.created_at >= "'$(date -u -d '24 hours ago' +%Y-%m-%dT%H:%M:%SZ)'" )' \
            > dependabot_alerts.json

      - name: Check if there are dependabot alerts
        id: check_alerts
        run: |
          COUNT=$(jq 'length' dependabot_alerts.json)
          echo "Dependabot alert count: $COUNT"
          if [ "$COUNT" -gt 0 ]; then
            echo "Dependabot alerts found!"
            exit 0
          else
            echo "✅ No new Dependabot alerts in the last 24 hours."
            exit 0
          fi
