name: Check Dependabot Alerts

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour (adjust as needed)
  workflow_dispatch: # Allows manual triggering

jobs:
  dependabot-alerts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: read # Required for Dependabot alerts

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Dependabot Alerts from the Last 24 Hours
        env:
          GH_TOKEN: ${{ secrets.DEPENDABOT }} # Uses the default GitHub Actions token
        run: |
          gh api repos/${{ github.repository }}/dependabot/alerts \
            --jq '.[] | select(.created_at >= "'$(date -u -d '24 hours ago' +%Y-%m-%dT%H:%M:%SZ)'" )' \
            > dependabot_alerts.json

          cat dependabot_alerts.json

      - name: Fail if there are new alerts
        run: |
          COUNT=$(jq 'length' dependabot_alerts.json)
          if [[ "$COUNT" -gt 0 ]]; then
            echo "🚨 $COUNT new Dependabot alerts found in the last 24 hours!"
            exit 1
          else
            echo "✅ No new Dependabot alerts in the last 24 hours."
          fi
