name: Create Asana Ticket for Dependabot Alerts

on:
  schedule:
    - cron: "16 17 * * *" # Runs daily at midnight UTC

jobs:
  check-alerts:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    steps:
      - name: Fetch Dependabot Alerts
        id: fetch-alerts
        run: |
          # Get alerts in JSON format
          alerts=$(gh api /repos/${{ github.repository }}/dependabot/alerts --jq '[.[] | select(.state == "open")]')
          echo "alerts=$alerts" >> $GITHUB_OUTPUT

      - name: Set output
        id: alerts-output
        run: |
          echo "count=$(echo '${{ steps.fetch-alerts.outputs.alerts }}' | jq length)" >> $GITHUB_OUTPUT

    outputs:
      alerts: ${{ steps.fetch-alerts.outputs.alerts }}
      alert-count: ${{ steps.alerts-output.outputs.count }}

  create-asana-task:
    runs-on: ubuntu-latest
    needs: check-alerts
    if: ${{ needs.check-alerts.outputs.alert-count > 0 }}
    permissions:
      security-events: read
    steps:
      - name: Process Alerts
        env:
          ALERTS_JSON: ${{ needs.check-alerts.outputs.alerts }}
        run: |
          echo "$ALERTS_JSON" > alerts.json
          # Add logic to process alerts.json here
      - name: Create Asana Task
        uses: honeycombio/gha-create-asana-task@main
        with:
          #asana-secret: ${{ secrets.ASANA_PAT }}
          asana-secret: 2/1207429301186131/1209370901760232:60206bd5140e2000ae39a1f75f21a90f
          #asana-workspace-id: ${{ secrets.ASANA_WORKSPACE_ID }}
          asana-workspace-id: 1209370921355179
          #asana-project-id: ${{ secrets.ASANA_PROJECT_ID }}
          asana-project-id: 1209370898900553
          #asana-section-id: ${{ secrets.ASANA_SECTION_ID }}
          asana-section-id: 1209370921355183
          asana-task-name: "Dependabot Alert: ${{ fromJson(needs.check-alerts.outputs.alerts)[0].security_advisory.summary }}"
          asana-task-description: |
            **Package:** ${{ fromJson(needs.check-alerts.outputs.alerts)[0].dependency.package.name }}
            **Severity:** ${{ fromJson(needs.check-alerts.outputs.alerts)[0].security_advisory.severity }}
            **Alert URL:** ${{ fromJson(needs.check-alerts.outputs.alerts)[0].html_url }}
